export interface ICompatibilityData {
  id: string;
  grandSeries: string;
  middleSeries: string;
  rowSeries: string;
  requiredSubjects: string[];
  encouragedSubjects: string[];
  mainSubjects: string[];
  referenceSubjects: string[];
}

/**
 * 계열적합성 데이터
 * 필수과목, 장려과목, 주요교과, 참조교과의 코드 배열을 가짐
 */
export const COMPATIBILITY_DATA: ICompatibilityData[] = [
  {
    id: "D11",
    grandSeries: "공학계열",
    middleSeries: "건축",
    rowSeries: "건축ㆍ설비공학",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "B14",
    grandSeries: "사회계열",
    middleSeries: "경영ㆍ경제",
    rowSeries: "광고·홍보학",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "F21",
    grandSeries: "의약계열",
    middleSeries: "간호",
    rowSeries: "간호학",
    requiredSubjects: ["HHS84", "HHS86"],
    encouragedSubjects: ["HHS85", "HHS87"],
    mainSubjects: ["HH5"],
    referenceSubjects: [],
  },
  {
    id: "D12",
    grandSeries: "공학계열",
    middleSeries: "건축",
    rowSeries: "건축학",
    requiredSubjects: ["HHS24"],
    encouragedSubjects: [],
    mainSubjects: ["HH2"],
    referenceSubjects: [],
  },
  {
    id: "B17",
    grandSeries: "사회계열",
    middleSeries: "경영ㆍ경제",
    rowSeries: "교양경상학",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "B11",
    grandSeries: "사회계열",
    middleSeries: "경영ㆍ경제",
    rowSeries: "경영학",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: ["HH2", "HH3"],
  },
  {
    id: "B12",
    grandSeries: "사회계열",
    middleSeries: "경영ㆍ경제",
    rowSeries: "경제학",
    requiredSubjects: [],
    encouragedSubjects: ["HHS17", "HHS24"],
    mainSubjects: ["HH2"],
    referenceSubjects: [],
  },
  {
    id: "G21",
    grandSeries: "예체능계열",
    middleSeries: "응용예술",
    rowSeries: "공예",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "C54",
    grandSeries: "교육계열",
    middleSeries: "중등교육",
    rowSeries: "공학교육",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: ["HH5"],
    referenceSubjects: [],
  },
  {
    id: "B13",
    grandSeries: "사회계열",
    middleSeries: "경영ㆍ경제",
    rowSeries: "관광학",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: ["HH3"],
  },
  {
    id: "B15",
    grandSeries: "사회계열",
    middleSeries: "경영ㆍ경제",
    rowSeries: "금융ㆍ회계ㆍ세무학",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "D61",
    grandSeries: "공학계열",
    middleSeries: "정밀ㆍ에너지",
    rowSeries: "광학공학",
    requiredSubjects: ["HHS17", "HHS24"],
    encouragedSubjects: ["HHS20"],
    mainSubjects: ["HH2", "HH5"],
    referenceSubjects: [],
  },
  {
    id: "B16",
    grandSeries: "사회계열",
    middleSeries: "경영ㆍ경제",
    rowSeries: "무역ㆍ유통학",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "D113",
    grandSeries: "공학계열",
    middleSeries: "기타",
    rowSeries: "교양공학",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: ["HH5"],
    referenceSubjects: [],
  },
  {
    id: "B38",
    grandSeries: "사회계열",
    middleSeries: "사회과학",
    rowSeries: "교양사회과학",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: ["HH4"],
    referenceSubjects: [],
  },
  {
    id: "D31",
    grandSeries: "공학계열",
    middleSeries: "교통ㆍ운송",
    rowSeries: "지상교통공학",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "D32",
    grandSeries: "공학계열",
    middleSeries: "교통ㆍ운송",
    rowSeries: "항공학",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "A28",
    grandSeries: "인문계열",
    middleSeries: "인문과학",
    rowSeries: "교양인문학",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "E46",
    grandSeries: "자연계열",
    middleSeries: "수학ㆍ물리ㆍ천문ㆍ지리",
    rowSeries: "교양자연과학",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: ["HH5"],
    referenceSubjects: [],
  },
  {
    id: "C11",
    grandSeries: "교육계열",
    middleSeries: "교육일반",
    rowSeries: "교육학",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "G62",
    grandSeries: "예체능계열",
    middleSeries: "음악",
    rowSeries: "국악",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "D33",
    grandSeries: "공학계열",
    middleSeries: "교통ㆍ운송",
    rowSeries: "해양공학",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "A26",
    grandSeries: "인문계열",
    middleSeries: "인문과학",
    rowSeries: "국제지역학",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "B32",
    grandSeries: "사회계열",
    middleSeries: "사회과학",
    rowSeries: "국제학",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: ["HH3"],
    referenceSubjects: [],
  },
  {
    id: "D42",
    grandSeries: "공학계열",
    middleSeries: "기계ㆍ금속",
    rowSeries: "금속공학",
    requiredSubjects: ["HHS17", "HHS24"],
    encouragedSubjects: ["HHS20"],
    mainSubjects: ["HH2", "HH5"],
    referenceSubjects: [],
  },
  {
    id: "D111",
    grandSeries: "공학계열",
    middleSeries: "기타",
    rowSeries: "기전공학",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "D41",
    grandSeries: "공학계열",
    middleSeries: "기계ㆍ금속",
    rowSeries: "기계공학",
    requiredSubjects: ["HHS24", "HHS20", "HHS104", "HHS105"],
    encouragedSubjects: ["HHS17"],
    mainSubjects: ["HH2", "HH5"],
    referenceSubjects: [],
  },
  {
    id: "G63",
    grandSeries: "예체능계열",
    middleSeries: "음악",
    rowSeries: "기악",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "D112",
    grandSeries: "공학계열",
    middleSeries: "기타",
    rowSeries: "응용공학",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "E11",
    grandSeries: "자연계열",
    middleSeries: "농림ㆍ수산",
    rowSeries: "농업학",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "E13",
    grandSeries: "자연계열",
    middleSeries: "농림ㆍ수산",
    rowSeries: "산림ㆍ원예학",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "G15",
    grandSeries: "예체능계열",
    middleSeries: "디자인",
    rowSeries: "기타디자인",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "G11",
    grandSeries: "예체능계열",
    middleSeries: "디자인",
    rowSeries: "디자인일반",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "G12",
    grandSeries: "예체능계열",
    middleSeries: "디자인",
    rowSeries: "산업디자인",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "D22",
    grandSeries: "공학계열",
    middleSeries: "토목ㆍ도시",
    rowSeries: "도시공학",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "G13",
    grandSeries: "예체능계열",
    middleSeries: "디자인",
    rowSeries: "시각디자인",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "G14",
    grandSeries: "예체능계열",
    middleSeries: "디자인",
    rowSeries: "패션디자인",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "G43",
    grandSeries: "예체능계열",
    middleSeries: "미술ㆍ조형",
    rowSeries: "조형",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "B31",
    grandSeries: "사회계열",
    middleSeries: "사회과학",
    rowSeries: "가족ㆍ사회ㆍ복지학",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "B33",
    grandSeries: "사회계열",
    middleSeries: "사회과학",
    rowSeries: "도시ㆍ지역학",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "B35",
    grandSeries: "사회계열",
    middleSeries: "사회과학",
    rowSeries: "언론ㆍ방송ㆍ매체학",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "G31",
    grandSeries: "예체능계열",
    middleSeries: "무용ㆍ체육",
    rowSeries: "무용",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "A21",
    grandSeries: "인문계열",
    middleSeries: "인문과학",
    rowSeries: "문헌정보학",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "E23",
    grandSeries: "자연계열",
    middleSeries: "생물ㆍ화학ㆍ환경",
    rowSeries: "동물ㆍ수의학",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "E22",
    grandSeries: "자연계열",
    middleSeries: "생물ㆍ화학ㆍ환경",
    rowSeries: "생물학",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "E24",
    grandSeries: "자연계열",
    middleSeries: "생물ㆍ화학ㆍ환경",
    rowSeries: "자원학",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "B21",
    grandSeries: "사회계열",
    middleSeries: "법률",
    rowSeries: "법학",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: ["HH4"],
  },
  {
    id: "F41",
    grandSeries: "의약계열",
    middleSeries: "치료ㆍ보건",
    rowSeries: "보건학",
    requiredSubjects: ["HHS84", "HHS86"],
    encouragedSubjects: ["HHS85", "HHS87"],
    mainSubjects: ["HH5"],
    referenceSubjects: [],
  },
  {
    id: "E31",
    grandSeries: "자연계열",
    middleSeries: "생활과학",
    rowSeries: "가정관리학",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "E34",
    grandSeries: "자연계열",
    middleSeries: "생활과학",
    rowSeries: "교양생활과학",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "B34",
    grandSeries: "사회계열",
    middleSeries: "사회과학",
    rowSeries: "사회학",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: ["HH4"],
  },
  {
    id: "E33",
    grandSeries: "자연계열",
    middleSeries: "생활과학",
    rowSeries: "의류ㆍ의상학",
    requiredSubjects: [],
    encouragedSubjects: ["HHS17", "HHS85", "HHS87"],
    mainSubjects: [],
    referenceSubjects: ["HH2", "HH5"],
  },
  {
    id: "D91",
    grandSeries: "공학계열",
    middleSeries: "산업",
    rowSeries: "산업공학",
    requiredSubjects: ["HHS24"],
    encouragedSubjects: ["HHS17"],
    mainSubjects: ["HH2"],
    referenceSubjects: [],
  },
  {
    id: "H11",
    grandSeries: "소속학과없음",
    middleSeries: "소속학과없음",
    rowSeries: "소속학과없음",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "E21",
    grandSeries: "자연계열",
    middleSeries: "생물ㆍ화학ㆍ환경",
    rowSeries: "생명과학",
    requiredSubjects: ["HHS24", "HHS84", "HHS85"],
    encouragedSubjects: ["HHS17", "HHS20", "HHS86", "HHS87"],
    mainSubjects: ["HH2", "HH5"],
    referenceSubjects: [],
  },
  {
    id: "D71",
    grandSeries: "공학계열",
    middleSeries: "소재ㆍ재료",
    rowSeries: "반도체ㆍ세라믹공학",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "D72",
    grandSeries: "공학계열",
    middleSeries: "소재ㆍ재료",
    rowSeries: "섬유공학",
    requiredSubjects: ["HHS24", "HHS84", "HHS86", "HHS87"],
    encouragedSubjects: ["HHS17", "HHS20", "HHS85"],
    mainSubjects: ["HH2", "HH5"],
    referenceSubjects: [],
  },
  {
    id: "G64",
    grandSeries: "예체능계열",
    middleSeries: "음악",
    rowSeries: "성악",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "E43",
    grandSeries: "자연계열",
    middleSeries: "수학ㆍ물리ㆍ천문ㆍ지리",
    rowSeries: "물리ㆍ과학",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "E12",
    grandSeries: "자연계열",
    middleSeries: "농림ㆍ수산",
    rowSeries: "수산학",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: ["HH5"],
  },
  {
    id: "E41",
    grandSeries: "자연계열",
    middleSeries: "수학ㆍ물리ㆍ천문ㆍ지리",
    rowSeries: "수학",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: ["HH2"],
    referenceSubjects: [],
  },
  {
    id: "G41",
    grandSeries: "예체능계열",
    middleSeries: "미술ㆍ조형",
    rowSeries: "순수미술",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "E45",
    grandSeries: "자연계열",
    middleSeries: "수학ㆍ물리ㆍ천문ㆍ지리",
    rowSeries: "지구ㆍ지리학",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "E44",
    grandSeries: "자연계열",
    middleSeries: "수학ㆍ물리ㆍ천문ㆍ지리",
    rowSeries: "천문ㆍ기상학",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "E32",
    grandSeries: "자연계열",
    middleSeries: "생활과학",
    rowSeries: "식품영양학",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "D73",
    grandSeries: "공학계열",
    middleSeries: "소재ㆍ재료",
    rowSeries: "신소재공학",
    requiredSubjects: ["HHS17", "HHS24"],
    encouragedSubjects: ["HHS20"],
    mainSubjects: ["HH2", "HH5"],
    referenceSubjects: [],
  },
  {
    id: "A23",
    grandSeries: "인문계열",
    middleSeries: "인문과학",
    rowSeries: "심리학",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "F31",
    grandSeries: "의약계열",
    middleSeries: "약학",
    rowSeries: "약학",
    requiredSubjects: ["HHS84", "HHS85", "HHS86", "HHS87"],
    encouragedSubjects: ["HHS17", "HHS24"],
    mainSubjects: ["HH2", "HH5"],
    referenceSubjects: [],
  },
  {
    id: "A112",
    grandSeries: "인문계열",
    middleSeries: "언어ㆍ문학",
    rowSeries: "교양어ㆍ문학",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "C51",
    grandSeries: "교육계열",
    middleSeries: "중등교육",
    rowSeries: "언어교육",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: ["HH1"],
    referenceSubjects: [],
  },
  {
    id: "A11",
    grandSeries: "인문계열",
    middleSeries: "언어ㆍ문학",
    rowSeries: "언어학",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: ["HH1"],
    referenceSubjects: [],
  },
  {
    id: "D62",
    grandSeries: "공학계열",
    middleSeries: "정밀ㆍ에너지",
    rowSeries: "에너지공학",
    requiredSubjects: ["HHS24", "HHS20", "HHS104", "HHS105"],
    encouragedSubjects: ["HHS17"],
    mainSubjects: ["HH2", "HH5"],
    referenceSubjects: [],
  },
  {
    id: "A12",
    grandSeries: "인문계열",
    middleSeries: "언어ㆍ문학",
    rowSeries: "국어ㆍ국문학",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "A15",
    grandSeries: "인문계열",
    middleSeries: "언어ㆍ문학",
    rowSeries: "기타아시아어ㆍ문학",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "A111",
    grandSeries: "인문계열",
    middleSeries: "언어ㆍ문학",
    rowSeries: "기타유럽어ㆍ문학",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "A17",
    grandSeries: "인문계열",
    middleSeries: "언어ㆍ문학",
    rowSeries: "독일어ㆍ문학",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "A18",
    grandSeries: "인문계열",
    middleSeries: "언어ㆍ문학",
    rowSeries: "러시아어ㆍ문학",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "A19",
    grandSeries: "인문계열",
    middleSeries: "언어ㆍ문학",
    rowSeries: "스페인어ㆍ문학",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "G61",
    grandSeries: "예체능계열",
    middleSeries: "음악",
    rowSeries: "음악학",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "A16",
    grandSeries: "인문계열",
    middleSeries: "언어ㆍ문학",
    rowSeries: "영미어ㆍ문학",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "G42",
    grandSeries: "예체능계열",
    middleSeries: "미술ㆍ조형",
    rowSeries: "응용미술",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "D82",
    grandSeries: "공학계열",
    middleSeries: "컴퓨터ㆍ통신",
    rowSeries: "응용소프트웨어공학",
    requiredSubjects: ["HHS17", "HHS24"],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "A13",
    grandSeries: "인문계열",
    middleSeries: "언어ㆍ문학",
    rowSeries: "일본어ㆍ문학",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "A14",
    grandSeries: "인문계열",
    middleSeries: "언어ㆍ문학",
    rowSeries: "중국어ㆍ문학",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "F11",
    grandSeries: "의약계열",
    middleSeries: "의료",
    rowSeries: "의학",
    requiredSubjects: ["HHS84"],
    encouragedSubjects: ["HHS17", "HHS24", "HHS20", "HHS85"],
    mainSubjects: ["HH2", "HH5"],
    referenceSubjects: [],
  },
  {
    id: "A110",
    grandSeries: "인문계열",
    middleSeries: "언어ㆍ문학",
    rowSeries: "프랑스어ㆍ문학",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "G51",
    grandSeries: "예체능계열",
    middleSeries: "연극ㆍ영화",
    rowSeries: "연극ㆍ영화",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "D43",
    grandSeries: "공학계열",
    middleSeries: "기계ㆍ금속",
    rowSeries: "자동차공학",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: ["HH5"],
    referenceSubjects: [],
  },
  {
    id: "C21",
    grandSeries: "교육계열",
    middleSeries: "유아교육",
    rowSeries: "유아교육학",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "G66",
    grandSeries: "예체능계열",
    middleSeries: "음악",
    rowSeries: "기타음악",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "G65",
    grandSeries: "예체능계열",
    middleSeries: "음악",
    rowSeries: "작곡",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "D74",
    grandSeries: "공학계열",
    middleSeries: "소재ㆍ재료",
    rowSeries: "재료공학",
    requiredSubjects: ["HHS24", "HHS20", "HHS104", "HHS86"],
    encouragedSubjects: ["HHS17", "HHS105", "HHS87"],
    mainSubjects: ["HH2", "HH5"],
    referenceSubjects: [],
  },
  {
    id: "G22",
    grandSeries: "예체능계열",
    middleSeries: "응용예술",
    rowSeries: "사진ㆍ만화",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "D51",
    grandSeries: "공학계열",
    middleSeries: "전기ㆍ전자",
    rowSeries: "전기공학",
    requiredSubjects: ["HHS17", "HHS24"],
    encouragedSubjects: ["HHS20"],
    mainSubjects: ["HH2", "HH5"],
    referenceSubjects: [],
  },
  {
    id: "G23",
    grandSeries: "예체능계열",
    middleSeries: "응용예술",
    rowSeries: "영상ㆍ예술",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "D52",
    grandSeries: "공학계열",
    middleSeries: "전기ㆍ전자",
    rowSeries: "전자공학",
    requiredSubjects: ["HHS17", "HHS24"],
    encouragedSubjects: ["HHS20"],
    mainSubjects: ["HH2", "HH5"],
    referenceSubjects: [],
  },
  {
    id: "A22",
    grandSeries: "인문계열",
    middleSeries: "인문과학",
    rowSeries: "문화ㆍ민속ㆍ미술사학",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "B36",
    grandSeries: "사회계열",
    middleSeries: "사회과학",
    rowSeries: "정치외교학",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: ["HH4"],
  },
  {
    id: "D53",
    grandSeries: "공학계열",
    middleSeries: "전기ㆍ전자",
    rowSeries: "제어계측공학",
    requiredSubjects: ["HHS17", "HHS24"],
    encouragedSubjects: ["HHS20"],
    mainSubjects: ["HH2", "HH5"],
    referenceSubjects: [],
  },
  {
    id: "D13",
    grandSeries: "공학계열",
    middleSeries: "건축",
    rowSeries: "조경학",
    requiredSubjects: ["HHS24", "HHS20", "HHS104"],
    encouragedSubjects: ["HHS17", "HHS105"],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "A24",
    grandSeries: "인문계열",
    middleSeries: "인문과학",
    rowSeries: "역사ㆍ고고학",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "A25",
    grandSeries: "인문계열",
    middleSeries: "인문과학",
    rowSeries: "종교학",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "A27",
    grandSeries: "인문계열",
    middleSeries: "인문과학",
    rowSeries: "철학ㆍ윤리학",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "C53",
    grandSeries: "교육계열",
    middleSeries: "중등교육",
    rowSeries: "사회교육",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "C56",
    grandSeries: "교육계열",
    middleSeries: "중등교육",
    rowSeries: "예체능교육",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "C52",
    grandSeries: "교육계열",
    middleSeries: "중등교육",
    rowSeries: "인문교육",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "C55",
    grandSeries: "교육계열",
    middleSeries: "중등교육",
    rowSeries: "자연계교육",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "G32",
    grandSeries: "예체능계열",
    middleSeries: "무용ㆍ체육",
    rowSeries: "체육",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "C41",
    grandSeries: "교육계열",
    middleSeries: "초등교육",
    rowSeries: "초등교육학",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "F12",
    grandSeries: "의약계열",
    middleSeries: "의료",
    rowSeries: "치의학",
    requiredSubjects: ["HHS84"],
    encouragedSubjects: ["HHS17", "HHS24", "HHS20", "HHS85"],
    mainSubjects: ["HH2", "HH5"],
    referenceSubjects: [],
  },
  {
    id: "D21",
    grandSeries: "공학계열",
    middleSeries: "토목ㆍ도시",
    rowSeries: "토목공학",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "E42",
    grandSeries: "자연계열",
    middleSeries: "수학ㆍ물리ㆍ천문ㆍ지리",
    rowSeries: "통계학",
    requiredSubjects: ["HHS17"],
    encouragedSubjects: [],
    mainSubjects: ["HH2"],
    referenceSubjects: [],
  },
  {
    id: "F43",
    grandSeries: "의약계열",
    middleSeries: "치료ㆍ보건",
    rowSeries: "의료공학",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "F42",
    grandSeries: "의약계열",
    middleSeries: "치료ㆍ보건",
    rowSeries: "재활학",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "D81",
    grandSeries: "공학계열",
    middleSeries: "컴퓨터ㆍ통신",
    rowSeries: "전산학ㆍ컴퓨터공학",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "F13",
    grandSeries: "의약계열",
    middleSeries: "의료",
    rowSeries: "한의학",
    requiredSubjects: ["HHS84"],
    encouragedSubjects: ["HHS85"],
    mainSubjects: [],
    referenceSubjects: ["HH5"],
  },
  {
    id: "D83",
    grandSeries: "공학계열",
    middleSeries: "컴퓨터ㆍ통신",
    rowSeries: "정보ㆍ통신공학",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "C31",
    grandSeries: "교육계열",
    middleSeries: "특수교육",
    rowSeries: "특수교육학",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: [],
  },
  {
    id: "B37",
    grandSeries: "사회계열",
    middleSeries: "사회과학",
    rowSeries: "행정학",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: ["HH4"],
  },
  {
    id: "E25",
    grandSeries: "자연계열",
    middleSeries: "생물ㆍ화학ㆍ환경",
    rowSeries: "화학",
    requiredSubjects: ["HHS24", "HHS86", "HHS87"],
    encouragedSubjects: ["HHS17", "HHS20"],
    mainSubjects: ["HH2", "HH5"],
    referenceSubjects: [],
  },
  {
    id: "D101",
    grandSeries: "공학계열",
    middleSeries: "화공",
    rowSeries: "화학공학",
    requiredSubjects: ["HHS24", "HHS20", "HHS104", "HHS105", "HHS84", "HHS86"],
    encouragedSubjects: ["HHS85", "HHS87"],
    mainSubjects: ["HH2", "HH5"],
    referenceSubjects: [],
  },
  {
    id: "E26",
    grandSeries: "자연계열",
    middleSeries: "생물ㆍ화학ㆍ환경",
    rowSeries: "환경학",
    requiredSubjects: [],
    encouragedSubjects: [],
    mainSubjects: [],
    referenceSubjects: ["HH5"],
  },
];
