export const susiComprehensiveExcelMapper = {
  id: 'unified_id',
  학년도: 'year',
  지역구분: 'region',
  대학명: 'university_name',
  대학코드: 'university_code',
  정원구분: 'national_or_private',
  기본유형: 'basic_type',
  전형세부유형: 'detailed_type',
  전형명: 'type_name',
  중심전형분류: 'central_classification',
  계열: 'department',
  모집단위명: 'recruitment_unit_name',

  대: 'large_department',
  중: 'medium_department',
  소: 'small_department',
  모집인원: 'recruitment_number',
  선발모형: 'selection_model',
  선발비율: 'selection_ratio',
  전형방법: 'selection_method',

  // 서류: 'document_rate',
  // 면접: 'interview_rate',
  그외비율: 'other_rate',
  그외내용: 'other_details',
  // '2단계_1단계성적': 'step2_step1_score_rate',
  // '2단계_면접비율': 'step2_interview_rate',
  '2단계_그외비율': 'step2_other_rate',
  '2단계_그외내용': 'step2_other_details',
  지원자격TEXT: 'application_eligibility_text',

  학종최초합등급컷_평균: 'cut_50',
  '학종추합등급컷_70%컷': 'cut_70',

  '등급컷위험도(+)5': 'risk_level_plus5',
  '위험도(+)4': 'risk_level_plus4',
  '위험도(+)3': 'risk_level_plus3',
  '위험도(+)2': 'risk_level_plus2',
  '위험도(+)1': 'risk_level_plus1',
  '위험도(-1)': 'risk_level_minus1',
  '위험도(-2)': 'risk_level_minus2',
  '위험도(-3)': 'risk_level_minus3',
  '위험도(-4)': 'risk_level_minus4',
  '위험도(-5)': 'risk_level_minus5',
  최저학력기준_반영여부: 'minimum_academic_standards_applied',
  수능최저학력기준TEXT: 'minimum_academic_standards_text',
  최저국어: 'minimum_korean',
  최저수학: 'minimum_math',
  '최저수학(미/기)': 'minimum_math_science_engineering',
  영어: 'minimum_english',
  사탐: 'minimum_social_studies',
  과탐: 'minimum_science_studies',
  탐계산: 'minimum_calculation_studies',
  최저갯수: 'minimum_count',
  최저합: 'minimum_sum',
  한국사: 'minimum_korean_history',
  그외: 'minimum_others',
  그외상세: 'minimum_others_details',

  '3개평가비중(학업/진로/공동)': 'evaluation_ratios',
  '3개평가코드': 'evaluation_code',

  면접점수반영여부: 'interview_score_applied',
  면접유형: 'interview_type',
  면접시활용자료: 'interview_resources',
  면접진행방식: 'interview_method',
  면접평가내용: 'interview_evaluation_content',
  면접날짜TEXT: 'interview_date_text',
  면접시간: 'interview_time',

  '2024년입결기준': 'admission_criteria_2024',
  '2024학년도입결(등급)': 'admission_2024_grade',
  '2024학년도입결(환산점수)': 'admission_2024_converted_score',
  '2024학년도경쟁률': 'competition_rate_2024',
  '2024충원': 'replenishment_2024',

  '2023학년도기준': 'admission_criteria_2023',
  '2023학년도입결(등급)': 'admission_2023_grade',
  '2023학년도입결(환산점수)': 'admission_2023_converted_score',
  '2023학년도경쟁률': 'competition_rate_2023',
  '2023충원': 'replenishment_2023',

  '2022학년도기준': 'admission_criteria_2022',
  '2022학년도입결': 'admission_2022_grade',
  '2022학년도경쟁률': 'competition_rate_2022',
  '2022충원': 'replenishment_2022',

  '2021학년도입결': 'admission_2021_grade',
  '2021학년도경쟁률': 'competition_rate_2021',
  '2021충원': 'replenishment_2021',

  '2020학년도입결': 'admission_2020_grade',
  '2020학년도경쟁률': 'competition_rate_2020',
  '2020충원': 'replenishment_2020',

  지원시유의사항: 'application_notes',
};
